version: "3.7"
services:
  mysql:
    image: mysql:5.7
    container_name: mysql
    environment:
      MYSQL_DATABASE: 'default'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'user'
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - ./logs:/var/log/mysql
      - ./data:/var/lib/mysql
      - ./configs/my.cnf:/etc/my.cnf
    networks:
      - default

networks:
  default:
    name: mysql

